"""Add gateway_payment_id and gateway_name to Payment model

Revision ID: 402a37749a7e
Revises: a22c49f4fdec
Create Date: 2025-12-24 13:24:52.008212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '402a37749a7e'
down_revision: Union[str, Sequence[str], None] = 'a22c49f4fdec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('gateway_payment_id', sa.String(length=255), nullable=True))
    op.add_column('payments', sa.Column('gateway_name', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'gateway_name')
    op.drop_column('payments', 'gateway_payment_id')
    # ### end Alembic commands ###
