"""add base_currency to client table

Revision ID: 4cdcc3bc994d
Revises: b0e73fb7ba8d
Create Date: 2025-12-24 19:08:10.650884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cdcc3bc994d'
down_revision: Union[str, Sequence[str], None] = 'b0e73fb7ba8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('base_currency', sa.String(length=10), nullable=False, server_default='INR'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'base_currency')
    # ### end Alembic commands ###
