"""Add password_hash and is_portal_enabled to Client model

Revision ID: a22c49f4fdec
Revises: fd9c3ca5ff73
Create Date: 2025-12-24 12:02:18.980096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a22c49f4fdec'
down_revision: Union[str, Sequence[str], None] = 'fd9c3ca5ff73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('password_hash', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('is_portal_enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'is_portal_enabled')
    op.drop_column('clients', 'password_hash')
    # ### end Alembic commands ###
