"""Add password reset fields to Client model

Revision ID: b0e73fb7ba8d
Revises: 402a37749a7e
Create Date: 2025-12-24 13:33:39.126986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0e73fb7ba8d'
down_revision: Union[str, Sequence[str], None] = '402a37749a7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('reset_password_token', sa.String(length=255), nullable=True))
    op.add_column('clients', sa.Column('reset_password_expires', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'reset_password_expires')
    op.drop_column('clients', 'reset_password_token')
    # ### end Alembic commands ###
