"""Add reminder settings and history tables

Revision ID: d6af8b3b632d
Revises: 4cdcc3bc994d
Create Date: 2025-12-27 12:58:17.880393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6af8b3b632d'
down_revision: Union[str, Sequence[str], None] = '4cdcc3bc994d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reminder_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('remind_before_due', sa.Text(), nullable=True),
    sa.Column('remind_on_due', sa.Boolean(), nullable=True),
    sa.Column('remind_after_due', sa.Text(), nullable=True),
    sa.Column('template_friendly', sa.Text(), nullable=True),
    sa.Column('template_due', sa.Text(), nullable=True),
    sa.Column('template_first_overdue', sa.Text(), nullable=True),
    sa.Column('template_second_overdue', sa.Text(), nullable=True),
    sa.Column('template_final_notice', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_reminder_settings_id'), 'reminder_settings', ['id'], unique=False)
    op.create_table('reminder_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('reminder_type', sa.String(length=50), nullable=False),
    sa.Column('recipient_email', sa.String(), nullable=False),
    sa.Column('email_subject', sa.String(), nullable=False),
    sa.Column('email_body', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reminder_history_id'), 'reminder_history', ['id'], unique=False)
    op.add_column('clients', sa.Column('base_currency', sa.String(length=10), nullable=False, server_default='INR'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'base_currency')
    op.drop_index(op.f('ix_reminder_history_id'), table_name='reminder_history')
    op.drop_table('reminder_history')
    op.drop_index(op.f('ix_reminder_settings_id'), table_name='reminder_settings')
    op.drop_table('reminder_settings')
    # ### end Alembic commands ###
